### ISSUE TITLE
Runtime exception related to permissions

### ISSUE THREAD

**Issue by ultrasamad** [TannerGabriel/android-sound-recorder#1]
I cloned the repository, built and run I got the below error on Logcat. I tested on  a real device running on android 9.

`2019-07-29 06:57:51.776 9144-9144/com.example.gabriel.soundrecorder E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.gabriel.soundrecorder, PID: 9144
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.gabriel.soundrecorder/com.example.gabriel.soundrecorder.MainActivity}: java.lang.RuntimeException: setAudioSource failed.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: setAudioSource failed.
        at android.media.MediaRecorder.setAudioSource(Native Method)
        at com.example.gabriel.soundrecorder.recorder.RecorderRepository.<init>(RecorderRepository.kt:55)
        at com.example.gabriel.soundrecorder.recorder.RecorderRepository$Companion.getInstance(RecorderRepository.kt:25)
        at com.example.gabriel.soundrecorder.util.InjectorUtils.provideRecorderViewModelFactory(InjectorUtil.kt:11)
        at com.example.gabriel.soundrecorder.MainActivity.initUI(MainActivity.kt:69)
        at com.example.gabriel.soundrecorder.MainActivity.onCreate(MainActivity.kt:31)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
`

**Comment by TannerGabriel** [comment]
Hey @ultrasamad ,

I think that this is an issue with the storage permission which has to be requested in realtime on newer Android versions. This can be done by checking if the permission has already been accepted in our MainActivity.kt file. If not you need to request it before proceeding to get the data from the internal storage.

I will fix it in the repository and push it to Github as fast as I can.

Kind regards,
Gabriel Tanner

**Comment by ultrasamad** [comment]
Oh that's cool. 😍

**Comment by TannerGabriel** [comment]
Should be fixed now. Try it out and tell me if it helped.

Kind regards,
Gabriel Tanner

**Comment by ultrasamad** [comment]
With the new updates, the app still crashes with below error in the logs:
```
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.gabriel.soundrecorder/com.example.gabriel.soundrecorder.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.gabriel.soundrecorder.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/base.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_resources_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/lib/arm64, /system/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3027)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3258)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7058)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
2019-08-07 20:05:32.849 19965-19965/? E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.gabriel.soundrecorder.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/base.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_resources_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at android.support.v4.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1219)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3015)
        	... 11 more
    	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:764)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:847)
        at android.app.LoadedApk.getResources(LoadedApk.java:1088)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2563)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6108)
        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1792)
        		... 6 more
2019-08-07 20:05:32.851 19965-19965/? E/AndroidRuntime: 	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/com.example.gabriel.soundrecorder-bwiGvv5N_8O36DYW-fMvxg==/split_lib_slice_7_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:764)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:847)
        at android.app.LoadedApk.getResources(LoadedApk.java:1088)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2563)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6108)
        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1792)
```

**Comment by ultrasamad** [comment]
Issue resolved. Thanks
